# Generated by Django 5.2 on 2025-06-25 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rota Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('delivery_areas', models.TextField(help_text='Virgülle ayırarak yazın', verbose_name='Teslimat Bölgeleri')),
                ('estimated_duration', models.IntegerField(default=60, verbose_name='Tahmini Süre (dakika)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Teslimat Rotası',
                'verbose_name_plural': 'Teslimat Rotaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Müşteri Adı')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Müşteri Telefon')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('in_production', 'Üretimde'), ('ready', 'Hazır'), ('out_for_delivery', 'Yolda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi'), ('returned', 'İade Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('requested_delivery_date', models.DateField(verbose_name='İstenen Teslimat Tarihi')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Teslimat Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('internal_notes', models.TextField(blank=True, help_text='Sadece personel görebilir', verbose_name='İç Notlar')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ara Toplam')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='İndirim Tutarı')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='KDV Tutarı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Toplam Tutar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Atanan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('assigned', 'Atandı'), ('in_progress', 'Yolda'), ('delivered', 'Teslim Edildi'), ('failed', 'Başarısız'), ('returned', 'İade Edildi')], default='planned', max_length=20, verbose_name='Durum')),
                ('delivery_address', models.TextField(verbose_name='Teslimat Adresi')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='Teslimat Telefon')),
                ('delivery_contact', models.CharField(max_length=200, verbose_name='Teslimat İletişim')),
                ('planned_start_time', models.DateTimeField(verbose_name='Planlanan Başlangıç')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç')),
                ('planned_end_time', models.DateTimeField(verbose_name='Planlanan Bitiş')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Bitiş')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Teslimat Notları')),
                ('customer_signature', models.TextField(blank=True, verbose_name='Müşteri İmza')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='Teslimat Fotoğrafı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Sürücü')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.deliveryroute', verbose_name='Rota')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Teslimat',
                'verbose_name_plural': 'Teslimatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Birim Fiyat')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='İndirim Oranı (%)')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Taslak'), ('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('in_production', 'Üretimde'), ('ready', 'Hazır'), ('out_for_delivery', 'Yolda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi'), ('returned', 'İade Edildi')], max_length=20, verbose_name='Önceki Durum')),
                ('to_status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('in_production', 'Üretimde'), ('ready', 'Hazır'), ('out_for_delivery', 'Yolda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi'), ('returned', 'İade Edildi')], max_length=20, verbose_name='Yeni Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Değiştirilme Tarihi')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Durum Geçmişi',
                'verbose_name_plural': 'Sipariş Durum Geçmişleri',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_templates', to='users.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sipariş Şablonu',
                'verbose_name_plural': 'Sipariş Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miktar')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notlar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='inventory.product', verbose_name='Ürün')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordertemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Sipariş Şablonu Kalemi',
                'verbose_name_plural': 'Sipariş Şablonu Kalemleri',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['requested_delivery_date'], name='orders_orde_request_a34c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='orders_orde_branch__e95c01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='ordertemplateitem',
            unique_together={('template', 'product')},
        ),
    ]
